site_name: Юпи!
site_url: http://docs.yupe.ru
repo_url: https://github.com/amyLabs/yupe-guides
site_description: Документация по платформе Юпи!
site_author: amylabs team
google_analytics: ['UA-61725465-4', 'docs.yupe.ru']
theme: readthedocs
theme_dir: themes/readthedocs
pages:
- 'О проекте':
    - 'Начало': 'index.md'
    - 'Знакомство с Yii': 'intro.md'
    - 'Помощь проекту': 'assistance.project.md'
    - 'Команда': 'team.md'
    - 'Как сделать ?': 'how.md'
- 'Введение':
    - 'Системные требования': 'hosting.md'
    - 'Установка': 'install.md'
    - 'Обновление': 'update.md'
- 'Модули':
    - 'Обзор модулей': 'modules.md'
    - 'Создание модуля': 'module-create.md'
- 'Настройки сайта': 'settings.md'
- 'Разработчику':
    - 'Мигратор': 'migrator.index.md'
    - 'Управление конфигами': 'config.manager.md'
    - 'Генерация Atom-ленты': 'atomfeed.md'
    - 'Проблемы CWebUser и модуля Gii': 'cwebuser.issues.md'
    - 'Работа с событиями': 'events.md'
    - 'Модуль поиска на основе Zend Lucene': 'zend.search.md'
    - 'Тестирование': 'testing.md'
    - 'Оптимальные настройки APC': 'apc.options.md'
    - 'Работа с eclipse': 'editors.eclipse.md'
    - 'Конфигурация Memcahed': 'memcached.md'
    - 'Установка на Linux': 'ubuntu.md'
    - 'Конфигурация модулей с настройками пользователей': 'userspace.config.md'
markdown_extensions:
    - admonition: