site_name: Yupe CMS
theme: readthedocs
theme_dir: themes/readthedocs
pages:
- 'Введение': 'index.md'
- 'Установка': 'install.md'
- 'Обновление': 'update.md'
- 'Обзор модулей': 'modules.md'
- 'Настройки сайта': 'settings.md'
